rename fee variables
element-fi/elf-simulations pull request #310
Opened 2023-03-24 20:30 UTC by wakamex

2023-03-27 17:32 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # TODO: test with redemption fees
redemption

2023-03-27 17:32 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # trade fee negative
trade

2023-03-27 17:32 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # redemption fee negative
redemption

2023-03-27 17:32 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # trade fee above 1
trade

2023-03-27 17:32 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # trade fee above 1
I'll not comment on the rest -- there are more in this file.

2023-03-27 17:34 UTC, dpaiton requested changes
I'm wondering what the plan is long-term: should we have a set of "fee" variables per market? will they all be specified as individual parameters? or maybe a "fees" data class or dictionary?

2023-03-27 17:34 UTC, dpaiton commented on tests/pricing_models/test_calc_in_given_out.py
>                      # trade fee above 1
also "fee percent" comments

2023-04-04 01:24 UTC, wakamex reviewed
lgtm, read through all the diffs

2023-04-04 01:27 UTC, merged